# Generated by Django 5.2.3 on 2025-06-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('tipo', models.CharField(choices=[('VOLUNTARIA', 'Participación Voluntaria'), ('SOLICITADA', 'Participación Solicitada'), ('EJERCICIO', 'Resolución de Ejercicio'), ('PRESENTACION', 'Presentación'), ('DEBATE', 'Participación en Debate')], db_index=True, default='VOLUNTARIA', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valor', models.PositiveSmallIntegerField(help_text='Valor de 1 a 10 que califica la calidad de la participación')),
            ],
            options={
                'verbose_name': 'Participación',
                'verbose_name_plural': 'Participaciones',
            },
        ),
    ]
