# Generated by Django 5.2.3 on 2025-06-13 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0002_initial'),
        ('participaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participacion',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'role': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.materia'),
        ),
        migrations.AddIndex(
            model_name='participacion',
            index=models.Index(fields=['estudiante', 'materia'], name='participaci_estudia_904200_idx'),
        ),
        migrations.AddIndex(
            model_name='participacion',
            index=models.Index(fields=['fecha'], name='participaci_fecha_37dfd8_idx'),
        ),
    ]
