# Generated by Django 5.2.3 on 2025-06-13 02:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_puntaje', models.DecimalField(decimal_places=2, help_text='Asistencia, disciplina, participaciones (10 puntos)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('saber_puntaje', models.DecimalField(decimal_places=2, help_text='Exámenes (35 puntos)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)])),
                ('hacer_puntaje', models.DecimalField(decimal_places=2, help_text='Tareas, prácticos (35 puntos)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)])),
                ('decidir_puntaje', models.DecimalField(decimal_places=2, help_text='Promedio de ser, saber y hacer (10 puntos)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('autoevaluacion_ser', models.DecimalField(decimal_places=2, default=0, help_text='Autoevaluación del estudiante para el ser (0-5 puntos)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('autoevaluacion_decidir', models.DecimalField(decimal_places=2, default=0, help_text='Autoevaluación del estudiante para el decidir (0-5 puntos)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('trimestre', models.CharField(choices=[('PRIMERO', 'Primer Trimestre'), ('SEGUNDO', 'Segundo Trimestre'), ('TERCERO', 'Tercer Trimestre')], max_length=10)),
                ('año_academico', models.CharField(help_text='Formato: AAAA-AAAA (ej: 2024-2025)', max_length=9)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
    ]
