# Generated by Django 5.2.3 on 2025-06-13 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0002_initial'),
        ('notas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'role': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nota',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.materia'),
        ),
        migrations.AlterUniqueTogether(
            name='periodo',
            unique_together={('trimestre', 'año_academico')},
        ),
        migrations.AddField(
            model_name='nota',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.periodo'),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('estudiante', 'materia', 'periodo')},
        ),
    ]
