# Generated by Django 5.2.3 on 2025-06-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='materias',
            field=models.ManyToManyField(related_name='cursos', to='materias.materia'),
        ),
    ]
